apiVersion: v1
kind: Service
metadata:
  name: aggregator
  labels:
    app: aggregator
spec:
  selector:
    app: aggregator
  ports:
    - name: http-metrics
      port: 4000
      targetPort: http-metrics
    - name: ws-internal
      port: 4001
      targetPort: ws-internal
    - name: http-health
      port: 4002
      targetPort: http-health
