apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - statefulset-master.yaml
  - statefulset-replica.yaml
  - statefulset-sentinel.yaml
  - service-master.yaml
  - service-replica.yaml
  - service-sentinel.yaml
  - prometheus-rule.yaml

commonLabels:
  app.kubernetes.io/part-of: stellar-oracle
  app.kubernetes.io/managed-by: kustomize
