apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: stellar-oracle-redis
  labels:
    app: redis-sentinel
    app.kubernetes.io/part-of: stellar-oracle
    app.kubernetes.io/component: redis
spec:
  selector:
    app: redis-sentinel
  ports:
    - name: sentinel
      port: 26379
      targetPort: sentinel
      protocol: TCP
  type: ClusterIP
