apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: stellar-oracle-tracing
  namespace: stellar-oracle
spec:
  tracing:
    - providers:
        - name: jaeger
      randomSamplingPercentage: 10
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-tracing-default
  namespace: istio-system
spec:
  tracing:
    - providers:
        - name: jaeger
      randomSamplingPercentage: 10
