apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml
  - rbac.yaml
  - configmap-pgbackrest.yaml
  - cronjob-restore-test.yaml
  - prometheus-rule.yaml
