apiVersion: v1
kind: ServiceAccount
metadata:
  name: timescaledb-patroni
  labels:
    app: timescaledb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: timescaledb-patroni
  labels:
    app: timescaledb
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "patch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "patch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: timescaledb-patroni
  labels:
    app: timescaledb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: timescaledb-patroni
subjects:
  - kind: ServiceAccount
    name: timescaledb-patroni
