graph LR
  timescaledb["timescaledb (database)"]
  aggregator["aggregator (service)"]
  api["api (service)"]
  chainlink["chainlink (external-oracle)"]
  redstone["redstone (external-oracle)"]
  band["band (external-oracle)"]
  reflector["reflector (external-oracle)"]
  soroban-contract["soroban-contract (blockchain)"]
  aggregator --> timescaledb
  api --> aggregator
  api --> timescaledb
  aggregator --> chainlink
  aggregator --> redstone
  aggregator --> band
  aggregator --> reflector
  aggregator --> soroban-contract
