/**
 * Provider-side Pact verification for the Price Feed API.
 *
 * This test starts the real Express app, replays the consumer pact file
 * against it, and verifies every interaction passes.
 *
 * Run:
 *   npm run pact:provider
 *
 * Requires the consumer pact to have been generated first:
 *   npm run pact:consumer
 */

import { Verifier, VerifierOptions } from '@pact-foundation/pact';
import * as path from 'path';
import * as http from 'http';

// ---------------------------------------------------------------------------
// Import the app — adjust the path if needed
// ---------------------------------------------------------------------------
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { app } = require('../../src/index');

const PORT = 4099; // dedicated port for pact verification

describe('Price Feed API — provider verification', () => {
  let server: http.Server;

  beforeAll((done) => {
    server = app.listen(PORT, done);
  });

  afterAll((done) => {
    server.close(done);
  });

  it('validates the consumer contract', async () => {
    const opts: VerifierOptions = {
      provider: 'StellarPriceOracleAPI',
      providerBaseUrl: `http://localhost:${PORT}`,

      // Load pact(s) from the local pacts directory (generated by consumer test)
      pactUrls: [
        path.resolve(
          __dirname,
          '../../pact/pacts/PriceFeedDashboard-StellarPriceOracleAPI.json'
        ),
      ],

      // Provider state handlers — set up the DB/fixtures each interaction needs
      stateHandlers: {
        'a price record exists for XLM_USD': async () => {
          // In a real test: seed the test DB with a known XLM_USD price row.
          // Here we rely on the test DB already being seeded by the test environment.
          return Promise.resolve('state set: XLM_USD price exists');
        },
        'no price record exists for UNKNOWN_PAIR': async () => {
          return Promise.resolve('state set: no UNKNOWN_PAIR price');
        },
        'historical price records exist for XLM_USD': async () => {
          return Promise.resolve('state set: XLM_USD history exists');
        },
      },

      logLevel: 'warn',
    };

    const result = await new Verifier(opts).verifyProvider();
    expect(result).toBeTruthy();
  }, 30_000);
});
