apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secrets.yaml
  - networkpolicy.yaml
  - aggregator/deployment.yaml
  - aggregator/service.yaml
  - aggregator/hpa.yaml
  - api/deployment-stable.yaml
  - api/deployment-canary.yaml
  - api/service.yaml
  - api/hpa.yaml
  - timescaledb/statefulset.yaml
  - timescaledb/service.yaml

commonLabels:
  app.kubernetes.io/part-of: stellar-oracle
  app.kubernetes.io/managed-by: kustomize
