apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stellar-oracle-dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: configmap-patch.yaml
  - target:
      kind: Deployment
      name: api-stable
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: api-canary
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: aggregator
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
